Q.No(1):

The values are :- hello  , -87.8

Expressions are :- * , - , / , +


Q.No(2):

Variable :-  In Python, a variable is a named location used to store data in
             memory

String :-  It is a data type in Python.


Q.No (3):

The three different data types in Python are

(i) Integers such as 1,2,3,4 etc.

(ii)Float such as 1.2 , 23.55, etc.

(iii)String such as "Student" "eacher" etc.


Q.No(4):

An expression is a combination of operators and operands that is interpreted to produce some other value. In any programming language, an expression is evaluated as per the precedence of its operators. So that if there is more than one operator in an expression, their precedence decides which operation will be performed first.

Example : x=10
          y=30
          sum=x+y  --------(this is an airthmatical expression )
          Print(sum)


 Q.No (5):

 An expression in Python is a piece of code that evaluates to a value such as 2 + 5 which evaluates to 7. A statement is a unit of execution or action, such as the assignment statement 'spam = 10', which assigns the value 10 to 'spam.


 Q.No(6):

 The bacon variable is set to 20. The bacon + 1 expression does not reassign the value in bacon (that would need an assignment statement: bacon = bacon + 1).

 Q.No(7)

 'spam' + 'spamspam' = spamspamspam

'spam' * 3 =
spam
spam
spam

Q.No(8)

it is so because variable names cannot start with a number.


Q.No(9):

The three functions are :-

(i) str()

(ii) int()

(iii) float()


Q.No(10):

'I have eaten ' + 99 + ' burritos.'
This expression causes and error because in this line 'I have eaten' and 'burritos' are strings, while 99 is treated as integer. In order to fix the error and print 'I have eaten 99 burritos.', 99 needs '' around it to treat it as a string by writing like this "I have eaten 99 burritos"